version: "3.8" # Specify the version of the Docker Compose file format

networks: # Define a custom network
  my_network:
    driver: bridge

services: # Services should be defined under the services key
  zookeeper:
    image: "bitnami/zookeeper:3.7.0-debian-10-r70"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my_network # Connect to the custom network

  kafka:
    image: "bitnami/kafka:2.8.0-debian-10-r42"
    ports:
      - "9093:9093" # Change to 9093 to access externally from your Windows host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - my_network # Connect to the custom network

  fastapi:
    build:
      context: ./api # Set context to the api directory
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=tiangolo/uvicorn-gunicorn-fastapi:python3.9
    image: fastapi
    ports:
      - "8001:80" # Map port 8001 on your host to port 80 in the container
    volumes:
      - ./api/app:/app # Mount the app directory
    networks:
      - my_network # Connect to the custom network
